services:
  payment-service:
    build:
      context: .
    volumes:
      - ./configs:/app/configs
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - bank-service_app-network


networks:
  bank-service_app-network:
    external: true